services:
  job:
    user: "${LOCAL_UID:-185}:${LOCAL_GID:-185}"
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID:-185}"
        LOCAL_GID: "${LOCAL_GID:-185}"
    volumes:
      - ./data:/data
    environment:
      - SPARK_MASTER
      - SPARK_DRIVER_MEMORY
      - SPARK_EXECUTOR_MEMORY
      - SPARK_EXECUTOR_CORES
      - SPARK_TOTAL_EXECUTOR_CORES
      - SPARK_SHUFFLE_PARTITIONS
  test:
    user: "${LOCAL_UID:-185}:${LOCAL_GID:-185}"
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID:-185}"
        LOCAL_GID: "${LOCAL_GID:-185}"
    entrypoint: ["python3", "-m", "unittest"]
    command: ["discover", "-s", "tests", "-v"]
