#!/usr/bin/env bash
# Bootstrap only Docker and autonomous fixtures; never download real archives.
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"
fail() { printf 'Setup failed: %s\n' "$*" >&2; exit 1; }
command -v docker >/dev/null 2>&1 || fail 'Docker is not installed or is not on PATH.'
docker compose version >/dev/null || fail 'Docker Compose v2 is required.'
[[ -f compose.yaml ]] || fail "Missing compose.yaml in $project_root."

# Never source .env: configuration must not execute shell code.
for key in LOCAL_UID LOCAL_GID; do
    value=''
    found=false
    if [[ -f .env ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
            line="${line%$'\r'}"
            if [[ "$line" =~ ^[[:space:]]*(export[[:space:]]+)?${key}= ]]; then
                value="${line#*=}"
                value="${value%%[[:space:]#]*}"
                value="${value#\"}"; value="${value%\"}"
                value="${value#\'}"; value="${value%\'}"
                found=true
            fi
        done < .env
    fi
    if [[ "$key" == LOCAL_UID && "${LOCAL_UID+x}" == x ]]; then value="$LOCAL_UID"; found=true; fi
    if [[ "$key" == LOCAL_GID && "${LOCAL_GID+x}" == x ]]; then value="$LOCAL_GID"; found=true; fi
    if [[ "$found" == true ]]; then
        [[ "$value" =~ ^[0-9]+$ ]] || fail "$key must be a nonempty numeric identity."
    fi
done
if [[ ! -e .env ]]; then
    runtime_uid="${LOCAL_UID-$(id -u)}"
    runtime_gid="${LOCAL_GID-$(id -g)}"
    [[ "$runtime_uid" != 0 ]] || fail 'Run setup as a non-root host user, or explicitly choose a non-root LOCAL_UID.'
    (set -o noclobber; printf '# Local Docker identity; generated by setup.sh.\nLOCAL_UID=%s\nLOCAL_GID=%s\n' "$runtime_uid" "$runtime_gid" > .env)
fi

compose() { docker compose --project-directory "$project_root" -f "$project_root/compose.yaml" "$@"; }
compose config --quiet
compose build
mkdir -p data
compose run --rm --entrypoint python3 job -c 'import os,tempfile; print("Runtime identity:",os.getuid(),os.getgid()); p=tempfile.NamedTemporaryFile(prefix=".setup-write-",dir="/data"); p.write(b"setup probe"); p.flush(); p.close(); print("PASS: data bind is writable; probe removed")' || fail 'The configured runtime cannot write data/. Set LOCAL_UID/LOCAL_GID for the directory owner in .env or your shell. Existing permissions were not changed.'
compose run --rm test
compose run --rm --entrypoint python3 job /app/scripts/check_reproducibility.py
printf 'PASS: setup, autonomous tests and generated-input CLI checks. No real data downloaded.\n'
